material_crud/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"), #admin/
    path('',include('sesion.urls')),
    path('',include('pedidos.urls')),
    
    
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedidos/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('',views.index, name='index'),
    path('obras/',login_required(views.obra), name='obras'),
    path('createobras/',login_required(views.create_obras), name='crear_obra'),
    path('pedidos/<int:pedido_id>/',login_required(views.pedidos_materialespedido), name='pedidos_detalle'),
    path('pedidos/aprobar/<int:pedido_id>/',login_required(views.pedidos_materialespedidoDir), name='pedidos_detalle_dir'),
    path('pedidos/<int:pedido_id>/descargar/', login_required(views.generar_archivo_xls), name='descargar'),
    path('pedidos/aprobar/<int:pedido_id>/descargar/sectores', login_required(views.generar_archivo_xlsDir), name='descargar_sectores'),
    path('pedidos/compras',login_required(views.pedidos), name='pedidos'),
    path('pedidos/aprobar',login_required(views.pedidosDir), name='pedidosDir'),
    path('pedidos/memoria/<int:pedido_id>/',login_required(views.memorias), name='memoria_detalle'),
    path('pedidos/memoria/',login_required(views.lista_memorias), name='lista_memoria'),
    # path('createpedido/',login_required(views.create_pedidos), name='crear_pedido'),
]

sesion/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    # path('signup/',views.signup, name='signup' ),
    path('logout/',login_required(views.logout_), name='logout'),
    path('signin/',views.signin, name='signin'),
]

pedidos/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
import os
from dotenv import load_dotenv
import google.generativeai as genai

load_dotenv()
token = os.environ.get('API_TOKEN')

class Obra(models.Model):
    areas_SOP = (('0','Escolar'),('1','Infraestructura'),('2','Intendencia'),('3','Salud'))
    name = models.CharField(max_length=200, verbose_name='Obra')
    location = models.CharField(max_length=200, verbose_name='Ubicación', blank=True, null=True)
    area = models.CharField('Area',max_length=1,choices=areas_SOP)
    dpto = models.CharField(max_length=150, blank=True, null=True, verbose_name='Departamento')
    localidad = models.CharField(max_length=150, blank=True, null=True, verbose_name='Localidad')
    municipio = models.CharField(max_length=150, blank=True, null=True, verbose_name='Municipio')
    frac = models.CharField(max_length=2, blank=True, null=True, verbose_name='Fracción')
    radio = models.CharField(max_length=2, blank=True, null=True, verbose_name='Radio')
    tipo = models.CharField(max_length=150, blank=True, null=True, verbose_name='Tipo')
    internacion = models.CharField(max_length=150, blank=True, null=True, verbose_name='Internación')
    nivel_sector = models.CharField(max_length=150, blank=True, null=True, verbose_name='Nivel/Sector')
    plaza = models.IntegerField(blank=True, null=True, verbose_name='Plaza')
    lugar = models.CharField(max_length=150, blank=True, null=True, verbose_name='Lugar')
    cue = models.IntegerField(blank=True, null=True, verbose_name='CUE')
    anexo = models.CharField(max_length=2, blank=True, null=True, verbose_name='Anexo')
    cp = models.CharField(max_length=5, blank=True, null=True, verbose_name='CP')
    periodo_func = models.CharField(max_length=150, blank=True, null=True, verbose_name='Periodo de Funcionamiento')
    geometry = models.CharField(max_length=150, blank=True, null=True, verbose_name='Georeferencia')
    class Meta:
        verbose_name = 'institución'
        verbose_name_plural = 'Intituciones'
        ordering = ['name']
    def __str__(self):
        return self.name

class Obra2(models.Model):
    name = models.ForeignKey(Obra, on_delete=models.CASCADE, verbose_name='Obra')
    codObra = models.CharField(max_length=200, verbose_name='Cod. Obra', blank=True, null=True)
    inspector = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Inspector')
    inicio = models.DateField(verbose_name='Fecha de inicio')
    plazo = models.IntegerField(verbose_name='Plazo')
    entrega = models.DateField(verbose_name='Fecha de entrega estimada', blank=True, null=True)
    finalizada = models.BooleanField(verbose_name='Finalizada', default=False)
    fecha_finalizada = models.DateField(verbose_name='Fecha de finalización real', blank=True, null=True)
    class Meta:
        verbose_name = 'obra2'
        verbose_name_plural = 'obras2'
        ordering = ['name']
    
    def __str__(self):
        return self.name.name
    
    def save(self, *args, **kwargs):
        self.codObra = f'{str(self.name.name)[:4].upper()}{str(self.id).zfill(4)}{str(self.name.dpto)[:3].upper()}'
        self.entrega = self.inicio + timedelta(days=self.plazo)
        super().save(*args, **kwargs)
class Sector(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Sector')
    class Meta:
        verbose_name = 'sector'
        verbose_name_plural = 'sectores'
        ordering = ['-id']
    def __str__(self):
        return self.name

class Rubros(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Rubro')
    referencia = models.CharField(max_length=150, blank=True, null=True, verbose_name='Referencia')
    class Meta:
        verbose_name = 'rubro'
        verbose_name_plural = 'rubros'
        ordering = ['name']
    def __str__(self):
        return self.name
class Material(models.Model): 
    name = models.CharField(max_length=150, verbose_name='Material', unique=True)
    unidad = models.CharField(max_length=20, verbose_name='Unidad')
    referencia = models.CharField(max_length=150, blank=True, null=True, verbose_name='Referencia')
    rubro = models.ForeignKey(Rubros, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Rubro')
    class Meta:
        verbose_name = 'insumo'
        verbose_name_plural = 'insumos'
        ordering = ['rubro','name']
    def __str__(self):
        return self.name+' - '+self.unidad
class Pedido(models.Model):
    obra = models.ForeignKey(Obra, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Tec asignado', blank=True, null=True)
    problema = models.TextField(max_length=6000, blank=True,null=True,verbose_name='Planteo de problema', help_text='Explicar brevemente el problema que quieres resolver.')
    propuesta = models.TextField(max_length=6000, blank=True,null=True,verbose_name='Propuesta de solución', help_text='Explicar brevemente la solución que quieres implementar.')
    memoria = models.TextField(max_length=3000, blank=True,null=True,verbose_name='Memoria', help_text='Memoria enriquecida sobre el problema', default="")
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')
    validated = models.BooleanField(default=False, verbose_name='Autorizado')
    a_proveedor = models.BooleanField(default=False, verbose_name='A Proveedor')
    orden_compra = models.CharField(max_length=20,unique=True ,blank=True,null=True, verbose_name='Orden de compra')
    materiales = models.ManyToManyField(
        Material,
        through='MaterialesPedido',
        blank=True,
    )
    def codigo_pedido(self):
        user_id = str(self.user)[:4].upper()
        return f'P{str(self.id)}{user_id}'
    class Meta:
        verbose_name = 'pedido'
        verbose_name_plural = 'pedidos'
        ordering = ['-id']
    def __str__(self):
        user_id = str(self.user)[:4].upper()
        return f'P{str(self.id)}{user_id} - {self.obra.name}'
    
    def save(self):
        if self.problema and self.propuesta:
            genai.configure(api_key=token)
            model = genai.GenerativeModel(model_name="gemini-pro")

            consulta = f'''Objetivo: Generar un informe tecnico del rubro de al construcción ordenado sobre una obra específica, incluyendo su nombre, introducción, problema principal, solución planteada,  desarrollo y conclusión final. No superar los 3000 caracteres.

Nombre de la obra: {self.obra.name.title()}
Problema: {self.problema}
Solución planteada: {self.propuesta}

Salida:

Informe:

Nombre de la obra: {self.obra.name.title()}

Introducción:
Contextualización del tema o ámbito en el que se enmarca la obra, presentación del problema principal que aborda la obra, importancia o relevancia del problema.

Problemática:
Descripción detallada del problema, incluyendo causas, consecuencias y posibles impactos. Análisis de las diferentes perspectivas o enfoques sobre el problema. Evidencia o datos que sustentan la problemática. Hasta 500 caracteres

Propuesta de intervención:
Descripción detallada de la solución propuesta para acondicionar la obra, incluyendo fundamentos o argumentos que la sustentan, posibles beneficios o ventajas de la solución y recursos necesarios para su implementación. Hasta 500 caracteres

Conclusión final:
Resumen de los puntos clave del informe. Reflexión sobre la viabilidad y potencial impacto de la solución propuesta. Aporte o valor de la obra para abordar el problema.
'''
            response = model.generate_content(consulta)
            self.memoria = response.text.replace("**", "")
        else:
            self.memoria = ""
        super().save()

class MaterialesPedido(models.Model): 
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, blank=True, null=True)
    material = models.ForeignKey(Material, on_delete=models.CASCADE, blank=True, null=True)
    cantidad = models.IntegerField()
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'material'
        verbose_name_plural = 'materiales'
        ordering = ['-id']
    def __str__(self):
        return self.pedido.obra.name

    

pedidos/forms.py
from django.forms import ModelForm
from .models import Obra, Pedido
from django import forms



class CrearObra(ModelForm):
    class Meta:
        model = Obra
        fields = ['name','location','area']

class PedidoForm(ModelForm):
    class Meta:
        model = Pedido
        fields = ['a_proveedor','orden_compra']
    
class PedidoFormDir(ModelForm):
    class Meta:
        model = Pedido
        fields = ['validated']

class MemoriaForm(ModelForm):
    class Meta:
        model = Pedido
        fields = ['problema','propuesta','memoria']

pedidos/templates/index.html
{% extends 'layouts/base.html' %}
{% block content %}
<section class="container">
    {% if request.user.is_authenticated %}
    <h1 class="display-1 text-center py-5">{{ titulo }}</h1>
    <div class="card border-0 py-5">
        <div class="row">
            <div class="col-md-6">
                <div class="card-body ">
                    <h5 class="card-title">Hola {% if user.first_name == '' %} {{user.username}} {% else %}
                        {{user.first_name | upper}} {% endif %}!</h5>
                    <p class="card-text">Bienvenido a la aplicación web para solicitud de pedidos de materiales del
                        Ministerio de Infraestructura y Obras Civiles. Esta web es para uso exclusivo del personal
                        autorizado por el ministerio. Aquí podrá gestionar sus solicitudes de forma rápida, fácil y
                        segura. Podrá consultar el estado de sus pedidos y el historial de sus operaciones. También
                        podrá comunicarse con el equipo técnico en caso de tener alguna duda o problema. Esperamos que
                        esta aplicación sea de gran utilidad y que ayude a optimizar tu trabajo.</p>
                    <p class="card-text"><small class="text-body-secondary"><i>Consultas por WhatsApp <a target="_blank"
                                    class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
                                    href="https://wa.me/5493834225785?text=Hola%20Lucas,%20tengo%20una%20duda...">aqui</a></i></small>
                    </p>
                </div>
            </div>
            <!-- metricas tecnicos -->
            {% if perms.pedidos.view_material %}
            <div class="col-md-6 text-end">
                <div class="row">
                    <div class="col-4">
                        <div class="row numbers">
                            <div class="col">
                                <div class="h1 fw-bold text-secondary">{{ cant_pedidos }} <i class="bi bi-send-arrow-up-fill"></i></div>
                                <p class="lead">Pedidos de Materiales</p>
                                <p class="text-muted">+11,06% vs mes anterior</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="row numbers">
                            <div class="col">
                                <div class="h1 fw-bold text-warning">{{ pedidos_aprobados }} <i class="bi bi-clipboard-check"></i></div>
                                <p class="lead">Pedidos Autorizados</p>
                                <p class="text-muted">{{ porc_aprobados }}% autorizado</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="row numbers">
                            <div class="col">
                                <div class="h1 fw-bold text-success">{{ pedidos_comprados }} <i class="bi bi-cart-plus-fill"></i></div>
                                <p class="lead">Pedidos comprados</p>
                                <p class="text-muted">{{ porc_comprados }}% resuelto</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Metricas compras -->
            {% elif perms.pedidos.add_material %}
            <div class="col-md-6 text-end">
                <div class="row">
                    <div class="col-4">
                        <div class="row numbers">
                            <div class="col">
                                <div class="h1 fw-bold text-secondary">{{ pedidos_aprobados }} <i class="bi bi-cart-fill"></i></div>
                                <p class="lead">Pedidos Solicitados</p>
                                <p class="text-muted">{{ var_pedido }}% vs mes anterior</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="row numbers">
                            <div class="col">
                                <div class="h1 fw-bold text-success">{{ pedidos_comprados }} <i class="bi bi-cart-check-fill"></i></div>
                                <p class="lead">Pedidos Gestionados</p>
                                <p class="text-muted">{{ porc_comprados }}% a proveedor</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="row numbers">
                            <div class="col">
                                <div class="h1 fw-bold text-danger">{{ pedidos_no_comprados }} <i class="bi bi-cart-x-fill"></i></div>
                                <p class="lead">Pedidos Pendientes</p>
                                <p class="text-muted">{{ porc_no_comprados }}% en mora</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Metricas directores -->
            {% elif perms.pedidos.add_sector %}
            <div class="col-md-6 text-end">
                <div class="row">
                    <div class="col-4">
                        <div class="row numbers">
                            <div class="col">
                                <div class="h1 fw-bold text-secondary">{{ cant_pedidos }} <i class="bi bi-check2"></i></div>
                                <p class="lead">Pedidos de Materiales</p>
                                <p class="text-muted">{{ var_pedido }}% vs mes anterior</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="row numbers">
                            <div class="col">
                                <div class="h1 fw-bold text-success">{{ pedidos_aprobados }} <i class="bi bi-check2-all"></i></div>
                                <p class="lead">Pedidos Autorizados</p>
                                <p class="text-muted">{{ porc_aprobados }}% a compra</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="row numbers">
                            <div class="col">
                                <div class="h1 fw-bold text-danger">{{ pedidos_pendientes }} <i class="bi bi-clock-history"></i></div>
                                <p class="lead">Pedidos Pendientes</p>
                                <p class="text-muted">{{ porc_pendientes }}% sin resolver</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>

    {% else %}
    <h1 class="display-1 text-center py-5">Uso restringido a personal autorizado ⚠️</h1>
    {% endif %}
    {% if user.is_authenticated %}

    {% else %}
    <div class="text-center">
        <a class="btn btn-secondary" href="/signin/">
            Iniciar sesión
        </a>
    </div>
    {% endif %}
</section>

{% endblock %}

pedidos/templates/lista_memoria.html
{% extends 'layouts/base.html' %}
{% block content %}

<main class="container py-5">
    <h1 class="display-1 text-center">Informes y memorias</h1>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-12 search">
                <form method="get">
                    <div id="custom-search-input">
                        <div class="input-group col-md-12">
                            <input type="text" class="form-control" placeholder="Ingrese palabras claves..."
                                name="buscar" value="{{ request.GET.buscar }}">
                            <span class="input-group-list">
                                <i class="icon icon-search"></i>
                                <button type="submit" class="btn btn-success">
                                    <i class="bi bi-search"></i> Buscar
                                </button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <hr size="5" color="grey" noshade>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="table-success">
                <th><input type="checkbox" id="select-all"></th>
                <th>Cod. Pedido</th>
                <th>Área</th>
                <th>Obra</th>
                <th>Problema</th>
                <th>Solución</th>
                <th>Memoria</th>
            </thead>
            <tbody>
                {% for lista in lista_memoria %}
                <tr>
                    <td><input type="checkbox" name="pedidos[]" value="{{ pedido.pk }}"></td>
                    <td>{{lista.codigo_pedido}}</a>
                    </td>
                    <td>{{lista.obra.get_area_display}}</td>
                    <td><a href= {{lista.id}}
                        class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">{{lista.obra}}</a></td>
                    <td>{% if lista.problema != '' %}✅{% else %}❌{% endif %}</td>
                    <td>{% if lista.propuesta != '' %}✅{% else %}❌{% endif %}</td>
                    <td>{% if lista.memoria != '' %}✅{% else %}❌{% endif %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

pedidos/templates/memoria.html
{% extends 'layouts/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main class="container py-5">
    <h1 class="display-1 text-center">Memoria de Obra {{memoria.obra.name}}</h1>
    <br>
    <div class="row">
        {% if request.method == 'GET' %}
        {% if perms.pedidos.view_pedido %}
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Planteo de problema</label>
                        <textarea name="problema" class="textarea form-control" rows="3"
                            placeholder="Explicar brevemente el problema que quieres resolver..."
                            id={{ form.problema }} </textarea>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Propuesta de solución</label>
                        <textarea name="propuesta" class="textarea form-control" rows="3"
                            placeholder="Explicar brevemente la solución que quieres implementar..."
                            id={{ form.propuesta }} </textarea>
                    </div>
                </div>
            </div>
            <br>
            <div class="col-sm-12">
                <div class="form-group">
                    <label>Memoria autogenerada</label>
                    <textarea name="memoria" class="textarea form-control" rows="3"
                        placeholder="Memoria enriquecida sobre problemas y soluciones enunciadas..." disabled='' style="height: 780px;"
                        id={{ form.memoria }} </textarea>
                </div>
            </div>
            <div class="d-flex justify-content-end mt-3">
                <button class="btn btn-success ms-2"><i class="bi bi-magic"></i> Generar memoria y guardar</button>
            </div>
        </form>
        {% endif %}
        {% endif %}
    </div>
    {{ error }}
    </div>
</main>
{% endblock %}

pedidos/templates/pedido.html
{% extends 'layouts/base.html' %}
{% block content %}

<main class="container py-5">
    <h1 class="display-1 text-center">Dirección de Compras</h1>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-12 search">
                <form method="get">
                    <div id="custom-search-input">
                        <div class="input-group col-md-12">
                            <input type="text" class="form-control" placeholder="Ingrese palabras claves..." name="buscar"
                                value="{{ request.GET.buscar }}">
                            <span class="input-group-list">
                                <i class="icon icon-search"></i>
                                <button type="submit" class="btn btn-success">
                                    <i class="bi bi-search"></i> Buscar
                                </button>
                            </span>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
    <hr size="5" color="grey" noshade>
    </class>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="table-success">
                <th>Cod. Pedido</th>
                <th>Área</th>
                <th>Obra</th>
                <th>A proveedor</th>
                <th>Orden de compra</th>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                <tr>
                    <td><a href="{% url 'pedidos_detalle' pedido.id %}"
                            class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">{{pedido.codigo_pedido}}</a>
                    </td>
                    <td>{{pedido.obra.get_area_display}}</td>
                    <td>{{pedido.obra}}</td>
                    <td>{% if pedido.a_proveedor == True %}✅{% else %}⌛{% endif %}</td>
                    <td>{% if pedido.orden_compra == null %} Sin asignar{% else %}{{pedido.orden_compra}}{% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>

{% endblock %}

pedidos/templates/pedidoDir.html
{% extends 'layouts/base.html' %}
{% block content %}

<main class="container py-5">
    <h1 class="display-1 text-center">Autorización de Pedidos</h1>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-12 search">
                <form method="get">
                    <div id="custom-search-input">
                        <div class="input-group col-md-12">
                            <input type="text" class="form-control" placeholder="Ingrese palabras claves..." name="buscar"
                                value="{{ request.GET.buscar }}">
                            <span class="input-group-list">
                                <i class="icon icon-search"></i>
                                <button type="submit" class="btn btn-success">
                                    <i class="bi bi-search"></i> Buscar
                                </button>
                            </span>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
    <hr size="5" color="grey" noshade>
    </class>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="table-success">
                <th>Cod. Pedido</th>
                <th>Área</th>
                <th>Obra</th>
                <th>Aprobado</th>
                <th>A proveedor</th>
                <th>Orden de compra</th>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                <tr>
                    <td><a href="{% url 'pedidos_detalle_dir' pedido.id %}"
                            class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">{{pedido.codigo_pedido}}</a>
                    </td>
                    <td>{{pedido.obra.get_area_display}}</td>
                    <td>{{pedido.obra}}</td>
                    <td>{% if pedido.validated == True %}✅{% else %}⌛{% endif %}</td>
                    <td>{% if pedido.a_proveedor == True %}✅{% else %}❌{% endif %}</td>
                    <td>{% if pedido.orden_compra == null %} Sin asignar{% else %}{{pedido.orden_compra}}{% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>

{% endblock %}

pedidos/templates/pedidos_materialespedido.html
{% extends 'layouts/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main class="container py-5">
    <h1 class="display-1 text-center">Pedido de Compra</h1>
    <br>
    <div class="row">
        <div class="col-12 col-lg-9">
            <h4>Obra: {{ obra_name }}</h4>
            <h6>Pedido: {{ cod_pedido }}</h6>
            <h6>Ubicacion: {{ ubicacion }}</h6>
            <br>
        </div>
        <div class="col-12 col-lg-3">
            {% if request.method == 'GET' %}
            {% if perms.pedidos.add_material %}
            <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-flex justify-content-end">
                    <button class="btn btn-success"><i class="bi bi-upload"></i> Guardar</button>
                </div>
                {% endif %}
            </form>
            {% endif %}
        </div>
        {{error}}
    </div>

    <hr size="5" color="grey" noshade>
    <table class="table table-striped">
        <div class="d-flex justify-content-end">
            <a href="descargar/" method="POST" class="btn btn-dark "><i class="bi bi-file-earmark-arrow-down"></i>
                Descargar</a>
        </div>
        <thead>
            <tr>
                <th>Rubro</th>
                <th>Material</th>
                <th>Unidad</th>
                <th>Cantidad</th>
            </tr>
        </thead>
        <tbody>
            {% for pedido_materialespedido in pedidos_materialespedido %}
            <tr>
                <td>{{ pedido_materialespedido.materialespedido__material__rubro__name }}</td>
                <td>{{ pedido_materialespedido.materialespedido__material__name }}</td>
                <td>{{ pedido_materialespedido.materialespedido__material__unidad }}</td>
                <td>{{ pedido_materialespedido.cantidad }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>

{% endblock %}

pedidos/templates/pedidos_materialespedidoDir.html
{% extends 'layouts/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main class="container py-5">
    <h1 class="display-1 text-center">Detalle del Pedido</h1>
    <br>
    <div class="row">
        <div class="col-12 col-lg-9">
            <h4>Obra: {{ obra_name }}</h4>
            <h6>Pedido: {{ cod_pedido }}</h6>
            <h6>Ubicacion: {{ ubicacion }}</h6>
            <h6>Memoria:</h6>
            {% if memoria == '' %}
            Sin especificar
            {% else %}
            <div class="card container">
                {{ memoria }}
            </div>
            {% endif %}
            <br>
        </div>
        <div class="col-12 col-lg-3">
            {% if request.method == 'GET' %}
            {% if perms.pedidos.add_sector %}
            {% if a_proveedor %}
            {% else %}
            <div class="d-flex justify-content-end">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-success"><i class="bi bi-upload"></i> Guardar</button>
                    {% endif %}
                </form>
            </div>
            {% endif %}
            {% endif %}
        </div>
        {{error}}
    </div>
    <hr size="5" color="grey" noshade>
    <table class="table table-striped">
        <div class="d-flex justify-content-end">
            <a href="descargar/sectores" method="POST" class="btn btn-dark "><i
                    class="bi bi-file-earmark-arrow-down"></i>
                Descargar</a>
        </div>
        <thead>
            <tr>
                <th>Sector</th>
                <th>Material</th>
                <th>Unidad</th>
                <th>Cantidad</th>
            </tr>
        </thead>
        <tbody>
            {% for pedido_materialespedido in pedidos_materialespedido %}
            <tr>
                <td>{{ pedido_materialespedido.materialespedido__sector__name }}</td>
                <td>{{ pedido_materialespedido.materialespedido__material__name }}</td>
                <td>{{ pedido_materialespedido.materialespedido__material__unidad }}</td>
                <td>{{ pedido_materialespedido.cantidad }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>

{% endblock %}